name: 'Docker Version - GitHub Actions LZU Auto COVID Health Report'
    
on:
  workflow_dispatch:  # Allow manual triggers
    inputs:
      delays:
        description: 'Delayed time (Optional) 可选延迟时间'
        required: false
# schedule:
#   - cron: '0 23 * 1,2,7,8 *' # Schedule on CST 7 everyday during Jan. Feb. Jul. Aug.

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: Star original repository if GPATOKEN set
          run: |
            curl \
            -X PUT \
            -H 'authorization: token ${{ secrets.GPATOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
            $GITHUB_API_URL/user/starred/HollowMan6/LZU-Auto-COVID-Health-Report
        - name: Auto COVID Health Report
          uses: HollowMan6/LZU-Auto-COVID-Health-Report@main
          with:
            CARDID: ${{ secrets.CARDID }}
            PASSWORD: ${{ secrets.PASSWORD }}
            DELAYS: ${{ github.event.inputs.delays }}
            SERVERCHANSCKEY: ${{ secrets.SERVERCHANSCKEY }}
            PPTOKEN: ${{ secrets.PPTOKEN }}
            PPTOPIC: ${{ secrets.PPTOPIC }}
            TGBOTTOKEN: ${{ secrets.TGBOTTOKEN }}
            TGCHATID: ${{ secrets.TGCHATID }}
            SUBSINFO: ${{ secrets.SUBSINFO }}
            CORPID: ${{ secrets.CORPID }}
            CORPSECRET: ${{ secrets.CORPSECRET }}
            AGENTID: ${{ secrets.AGENTID }}
        - name: 'Re-run workflow if failed and GPATOKEN set'
          if: ${{ failure() }}
          run: |
            workflow_url=`curl $GITHUB_API_URL/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | grep workflow_url | cut -d \" -f 4` \
            && curl \
            -X POST \
            -H 'authorization: token ${{ secrets.GPATOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
            $workflow_url/dispatches \
            -d '{"ref":"${{ github.ref }}", "inputs": { "delays": "30m" }}'
